### ISSUE TITLE
SSID not changing

### ISSUE THREAD

**Issue by ShahriarShafin** [Alpha-1729/ESP_WiFi_Captive_Portal#3]
when I'm trying to change the SSID the postSSID page not loading.

**Comment by 125K** [comment]
<img src="https://i.imgur.com/Fslj38f.png"></img>

**Comment by Alpha-1729** [comment]
After you change the SSID , please connect to the new SSID.

**Comment by Alpha-1729** [comment]
Which method did you use?
flash the bin file or upload the code.

**Comment by Alpha-1729** [comment]
> 
> 
> when I'm trying to change the SSID the postSSID page not loading.

Contact through this https://alpha-1729.github.io/Alpha-1729/index.html

**Comment by ShahriarShafin** [comment]
Thank you guys. It’s working now. 😊

**Comment by Faisal-076** [comment]
Brother please give the link
